"""add knockout_lists_frozen

Revision ID: 23cfa550d89e
Revises: a1b2c3d4e5f6
Create Date: 2026-01-19 08:37:03.774125

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23cfa550d89e"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "leagues",
        sa.Column(
            "knockout_lists_frozen",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leagues", "knockout_lists_frozen")
    # ### end Alembic commands ###
