"""add group_phase_ended

Revision ID: 278d90a8718e
Revises: d135e2d41fb8
Create Date: 2026-01-16 13:32:53.264540

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "278d90a8718e"
down_revision: Union[str, None] = "d135e2d41fb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "leagues",
        sa.Column(
            "group_phase_ended", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leagues", "group_phase_ended")
    # ### end Alembic commands ###
