"""add league player limits and knockout config

Revision ID: 2c2f0c70988f
Revises: 3fece1b0ecca
Create Date: 2026-01-16 12:46:50.506843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c2f0c70988f"
down_revision: Union[str, None] = "3fece1b0ecca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add server defaults for existing rows
    op.add_column(
        "leagues",
        sa.Column("min_players", sa.Integer(), nullable=False, server_default="8"),
    )
    op.add_column("leagues", sa.Column("max_players", sa.Integer(), nullable=True))
    op.add_column(
        "leagues",
        sa.Column(
            "has_knockout_phase", sa.Boolean(), nullable=False, server_default="true"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leagues", "has_knockout_phase")
    op.drop_column("leagues", "max_players")
    op.drop_column("leagues", "min_players")
    # ### end Alembic commands ###
