"""leagues init

Revision ID: 3fece1b0ecca
Revises: 1c15de50890f
Create Date: 2026-01-16 12:31:45.908595

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3fece1b0ecca"
down_revision: Union[str, None] = "1c15de50890f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults for existing rows
    op.add_column(
        "leagues",
        sa.Column("min_group_size", sa.Integer(), nullable=False, server_default="4"),
    )
    op.add_column(
        "leagues",
        sa.Column("max_group_size", sa.Integer(), nullable=False, server_default="6"),
    )
    op.add_column("leagues", sa.Column("knockout_size", sa.Integer(), nullable=True))
    op.drop_column("leagues", "registration_start")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "leagues",
        sa.Column(
            "registration_start",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("leagues", "knockout_size")
    op.drop_column("leagues", "max_group_size")
    op.drop_column("leagues", "min_group_size")
    # ### end Alembic commands ###
