"""add army list fields

Revision ID: 9aa13348795f
Revises: 23cfa550d89e
Create Date: 2026-01-19 11:17:24.066274

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9aa13348795f"
down_revision: Union[str, None] = "23cfa550d89e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "league_players", sa.Column("group_army_list", sa.Text(), nullable=True)
    )
    op.add_column(
        "league_players",
        sa.Column("group_list_submitted_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "leagues",
        sa.Column(
            "has_group_phase_lists",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "leagues",
        sa.Column(
            "has_knockout_phase_lists",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    op.add_column(
        "leagues",
        sa.Column(
            "group_lists_frozen", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "leagues",
        sa.Column(
            "group_lists_visible", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leagues", "group_lists_visible")
    op.drop_column("leagues", "group_lists_frozen")
    op.drop_column("leagues", "has_knockout_phase_lists")
    op.drop_column("leagues", "has_group_phase_lists")
    op.drop_column("league_players", "group_list_submitted_at")
    op.drop_column("league_players", "group_army_list")
    # ### end Alembic commands ###
