"""add days_per_match

Revision ID: d135e2d41fb8
Revises: 2c2f0c70988f
Create Date: 2026-01-16 13:19:44.166471

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d135e2d41fb8"
down_revision: Union[str, None] = "2c2f0c70988f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "leagues",
        sa.Column("days_per_match", sa.Integer(), nullable=False, server_default="14"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leagues", "days_per_match")
    # ### end Alembic commands ###
